[
  {
    name: "City Centre Bahrain",
    region: "Capital",
    category: "thingsToDo",
    subTags: [
      "shopping mall",
      "retail therapy",
      "dining options",
      "entertainment facilities",
      "cinema",
      "family-friendly",
      "socializing",
      "modern",
      "indoor activities",
      "leisure",
      "tourist attraction",
    ],
    rate: 4,
    location: "Manama, Bahrain",
    googleLocation: {
      lat: 26.2307,
      lng: 50.5832,
      placeId: null,
    },
    description:
      "City Centre Bahrain is a large shopping mall in Manama featuring a wide range of international retail brands, diverse dining options, and entertainment facilities. It is described as family-friendly and perfect for both shopping and entertainment.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "", // Placeholder image
    type: "Shopping Mall",
    priceRange: "20 - 100 BHD",
    email: "info@citycentrebahrain.com", // Dummy data
    phoneNumber: "+973 1234 5678", // Dummy data
    website: "citycentrebahrain.com",

    // Optional fields for ThingsToDo
    locationRate: 0,
    safety: 0,
    facilities: 0,
    convenience: 0,
    staff: 0,
    duration: "3 - 4 hours",
    activityType: ["shopping", "dining", "cinema"],
    accessibility: [
      "Wheelchair Accessible",
      "Family-Friendly",
      "Food and Beverage Options",
    ],
    whatToExpect: [
      "Wide selection of shops",
      "Dining options",
      "Entertainment activities",
      "Family-friendly environment",
    ],
  },
  {
    name: "Al-Fateh Grand Mosque",
    region: "Capital",
    category: "thingsToDo",
    subTags: [
      "religious site",
      "cultural landmark",
      "guided tours",
      "architecture",
      "family",
      "solo",
      "duo",
      "friends",
      "Islamic art",
      "heritage",
      "educational",
    ],
    rate: 5, // Based on it being a top-rated attraction
    location: "Manama, Bahrain",
    googleLocation: {
      lat: 26.2154,
      lng: 50.595,
      placeId: null,
    },
    description:
      "Al-Fateh Grand Mosque is one of the largest mosques in the world, welcoming visitors of all faiths to explore its majestic architecture and learn about Islamic culture through guided tours.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Religious Site",
    priceRange: "Free",
    email: "info@alfatehmosque.org", // Dummy data
    phoneNumber: "+973 1772 7773", // Dummy data
    website: "alfatehmosque.org",

    // Optional fields for ThingsToDo
    locationRate: 0,
    safety: 0,
    facilities: 0,
    convenience: 0,
    staff: 0,
    duration: "1 - 2 hours",
    activityType: ["guided tours", "cultural education", "photography"],
    accessibility: [
      "Wheelchair Accessible",
      "Family-Friendly",
      "Guided Tours Available",
    ],
    whatToExpect: [
      "Insight into Islamic faith",
      "Architectural grandeur",
      "Cultural immersion",
      "Educational tours",
    ],
  },
  {
    name: "Tree of Life",
    region: "Southern",
    category: "thingsToDo",
    subTags: [
      "natural wonder",
      "desert",
      "ancient tree",
      "miracle",
      "family",
      "solo",
      "friends",
      "photography",
      "nature",
      "cultural significance",
      "landmark",
    ],
    rate: 4,
    location: "Manama, Bahrain",
    googleLocation: {
      lat: 26.0667,
      lng: 50.5577,
      placeId: null,
    },
    description:
      "The Tree of Life in Bahrain is a remarkable natural wonder, standing alone in the desert with no clear water source nearby. This ancient tree, around 400 years old, has become a symbol of survival and resilience.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Natural Site",
    priceRange: "Free",
    email: "info@treeoflife.bh", // Dummy data
    phoneNumber: "+973 0000 0000", // Dummy data
    website: "treeoflife.bh",

    // Optional fields for ThingsToDo
    locationRate: 0,
    safety: 0,
    facilities: 0,
    convenience: 0,
    staff: 0,
    duration: "0.5 - 1 hour",
    activityType: ["sightseeing", "photography"],
    accessibility: ["Wheelchair Accessible", "Pet-Friendly", "Family-Friendly"],
    whatToExpect: [
      "Unique natural sight",
      "Photographic opportunities",
      "Educational plaques on site",
      "Desert environment",
    ],
  },
  {
    name: "Bab el-Bahrain Souk",
    region: "Capital",
    category: "thingsToDo",
    subTags: [
      "traditional market",
      "shopping",
      "souvenirs",
      "cultural experience",
      "gold souk",
      "local crafts",
      "family",
      "friends",
      "solo",
      "duo",
      "bargain",
    ],
    rate: 4,
    location: "Manama, Bahrain",
    googleLocation: {
      lat: 26.237,
      lng: 50.576,
      placeId: null,
    },
    description:
      "Bab el-Bahrain Souk, located in the heart of Manama, offers a traditional marketplace experience with a variety of shops selling everything from gold to local crafts. The souk is known for its vibrant atmosphere and is a must-visit for those looking to explore Bahraini culture and history.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Marketplace",
    priceRange: "Variable",
    email: "contact@babelelbahrain.bh", // Dummy data
    phoneNumber: "+973 1234 5678", // Dummy data
    website: "babelelbahrain.bh",

    // Optional fields for ThingsToDo
    locationRate: 0,
    safety: 0,
    facilities: 0,
    convenience: 0,
    staff: 0,
    duration: "1 - 3 hours",
    activityType: ["shopping", "cultural exploration"],
    accessibility: ["Wheelchair Accessible", "Pet-Friendly", "Family-Friendly"],
    whatToExpect: [
      "Vibrant market life",
      "Cultural immersion",
      "Opportunity to bargain",
      "Diverse range of products",
    ],
  },
  {
    name: "Bahrain International Circuit",
    region: "Southern",
    category: "thingsToDo",
    subTags: [
      "auto racing",
      "F1 Grand Prix",
      "motorsport events",
      "adrenaline",
      "entertainment",
      "family",
      "friends",
      "solo",
      "sports event",
      "outdoor",
      "exciting",
    ],
    rate: 4.5,
    location:
      "Gate 255, Gulf of Bahrain Avenue, Umm Jidar, Manama 1062, Bahrain",
    googleLocation: {
      lat: 26.0325,
      lng: 50.5106,
      placeId: null,
    },
    description:
      "The Bahrain International Circuit is a premier venue for auto racing, including the prestigious Formula One Grand Prix. Known for its world-class facilities and thrilling motorsport events, it provides an exhilarating experience for fans and participants alike.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Racing Track",
    priceRange: "Varies by event",
    email: "info@bahraingp.com", // Dummy data
    phoneNumber: "+973 1745 0000", // Dummy data
    website: "bahraingp.com",

    // Optional fields for ThingsToDo
    locationRate: 0,
    safety: 0,
    facilities: 0,
    convenience: 0,
    staff: 0,
    duration: "2 - 4 hours",
    activityType: ["watching races", "participating in events"],
    accessibility: [
      "Wheelchair Accessible",
      "Family-Friendly",
      "Pet-Friendly",
      "Food and Beverage Options",
    ],
    whatToExpect: [
      "High-speed races",
      "Adrenaline-pumping action",
      "Sophisticated facilities",
      "Memorable experiences",
    ],
  },
  {
    name: "The Lost Paradise of Dilmun Water Park",
    region: "Southern",
    category: "thingsToDo",
    subTags: [
      "water park",
      "slides",
      "family-friendly",
      "swimming",
      "water attractions",
      "adventure",
      "entertainment",
      "outdoor",
      "refreshing",
      "summer",
      "leisure",
    ],
    rate: 4.5,
    location: "Building 1663, Road 6227, Block 1062, Zallaq 00973, Bahrain",
    googleLocation: {
      lat: 26.0684,
      lng: 50.5065,
      placeId: null,
    },
    description:
      "As Bahrain's largest water park, The Lost Paradise of Dilmun covers 77,000 square meters and offers a historically themed experience with over 18 slides and attractions that blend into a desert oasis setting for all ages to enjoy.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Water Park",
    priceRange: "15 - 30 BHD",
    email: "info@lpodwaterpark.bh", // Dummy data
    phoneNumber: "+973 1784 5100", // Dummy data
    website: "lpodwaterpark.bh",

    // Optional fields for ThingsToDo
    locationRate: 0,
    safety: 0,
    facilities: 0,
    convenience: 0,
    staff: 0,
    duration: "More than 3 hours",
    activityType: ["swimming", "water sliding", "relaxing"],
    accessibility: [
      "Wheelchair Accessible",
      "Family-Friendly",
      "First Aid Available",
    ],
    whatToExpect: [
      "Fun water slides",
      "Family entertainment",
      "Themed decorations",
      "Relaxing water rides",
    ],
  },
  {
    name: "Qal'at al-Bahrain",
    region: "Capital",
    category: "thingsToDo",
    subTags: [
      "historical site",
      "UNESCO World Heritage",
      "archaeology",
      "sunset views",
      "family-friendly",
      "cultural",
      "educational",
      "guided tours available",
    ],
    rate: 4,
    location: "Bahrain",
    googleLocation: {
      lat: 26.2361,
      lng: 50.5475,
      placeId: null,
    },
    description:
      "Qal'at al-Bahrain, also known as the Bahrain Fort or Portuguese Fort, is a historical archaeological site that dates back to the Dilmun era. It offers visitors a glimpse into Bahrain's rich history and stunning sunset views over the sea.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Historical Fort",
    priceRange: "Free entry",
    email: "info@qalatalbahrain.bh", // Dummy data
    phoneNumber: "+973 1234 5678", // Dummy data
    website: "qalatalbahrain.bh",

    // Optional fields for ThingsToDo
    locationRate: 0,
    safety: 0,
    facilities: 0,
    convenience: 0,
    staff: 0,
    duration: "2 - 3 hours",
    activityType: ["history tours", "photography", "sightseeing"],
    accessibility: [
      "Wheelchair Accessible",
      "Family-Friendly",
      "Guided Tours Available",
    ],
    whatToExpect: [
      "Rich historical experience",
      "Educational tours",
      "Beautiful sea views",
      "Cultural immersion",
    ],
  },
  {
    name: "Arad Fort",
    region: "Muharraq",
    category: "thingsToDo",
    subTags: [
      "historical site",
      "fort",
      "cultural heritage",
      "photography spot",
      "family-friendly",
      "friends",
      "solo",
      "discover",
      "architecture",
    ],
    rate: 4,
    location: "Arad, Muharraq, Bahrain",
    googleLocation: {
      lat: 26.2675,
      lng: 50.6206,
      placeId: null,
    },
    description:
      "Arad Fort is a 15th-century fort in Arad, Bahrain. Originally built in a typical Islamic style, the fort has been the site of various historical events. It's a popular spot for learning about Bahrain's rich history and for enjoying scenic views.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Fort",
    priceRange: "Free entry",
    email: "info@aradfort.bh",
    phoneNumber: "+973 1234 5678",
    website: "aradfort.bh",
    locationRate: 0,
    safety: 0,
    facilities: 0,
    convenience: 0,
    staff: 0,
    duration: "1 - 2 hours",
    activityType: ["sightseeing", "historical tours", "educational tours"],
    accessibility: ["Wheelchair Accessible", "Family-Friendly", "Pet-Friendly"],
    whatToExpect: [
      "Historical tours",
      "Photography opportunities",
      "Cultural insights",
    ],
  },
  {
    name: "Bahrain Military Museum",
    region: "Riffa",
    category: "thingsToDo",
    subTags: [
      "museum",
      "military history",
      "educational",
      "family-friendly",
      "friends",
      "solo",
      "discover",
      "historical artifacts",
    ],
    rate: 4,
    location: "Riffa, Bahrain",
    googleLocation: {
      lat: 26.1305,
      lng: 50.555,
      placeId: null,
    },
    description:
      "The Bahrain Military Museum in Riffa showcases Bahrain's military history from ancient times to the present. Exhibits include military paraphernalia and historical artifacts, making it a fascinating visit for history enthusiasts.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Museum",
    priceRange: "Free entry",
    email: "info@bahrainmilitarymuseum.bh",
    phoneNumber: "+973 1234 5678",
    website: "bahrainmilitarymuseum.bh",
    locationRate: 0,
    safety: 0,
    facilities: 0,
    convenience: 0,
    staff: 0,
    duration: "1 - 2 hours",
    activityType: ["guided tours", "self-guided tours", "educational programs"],
    accessibility: ["Wheelchair Accessible", "Family-Friendly", "Informative"],
    whatToExpect: [
      "Guided tours",
      "Military artifacts",
      "Educational exhibits",
    ],
  },
  {
    name: "National Theatre of Bahrain",
    region: "Capital",
    category: "thingsToDo",
    subTags: [
      "performing arts",
      "theatre",
      "cultural",
      "entertainment",
      "shows",
      "live performances",
      "family-friendly",
      "friends",
      "solo",
    ],
    rate: 5,
    location: "Manama, Bahrain",
    googleLocation: {
      lat: 26.2333,
      lng: 50.5714,
      placeId: null,
    },
    description:
      "The National Theatre of Bahrain, a landmark of cultural architecture, hosts a variety of performances, from traditional to modern theatrical shows. It's renowned for its acoustics and modern facilities, offering a rich experience to arts enthusiasts.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Theatre",
    priceRange: "Varies by show",
    email: "info@nationaltheatre.bh",
    phoneNumber: "+973 1234 5678",
    website: "nationaltheatre.bh",
    locationRate: 0,
    safety: 0,
    facilities: 0,
    convenience: 0,
    staff: 0,
    duration: "2 - 3 hours",
    activityType: ["watching performances", "attending cultural events"],
    accessibility: [
      "Wheelchair Accessible",
      "Family-Friendly",
      "High-Quality Acoustics",
    ],
    whatToExpect: [
      "Stunning performances",
      "Cultural diversity",
      "High-quality productions",
    ],
  },
  {
    name: "Gravity Indoor Skydiving",
    region: "Capital",
    category: "thingsToDo",
    subTags: [
      "adventure sports",
      "indoor skydiving",
      "thrill-seeking",
      "unique experience",
      "family-friendly",
      "friends",
      "solo",
      "safe",
    ],
    rate: 5,
    location: "Manama, Bahrain",
    googleLocation: {
      lat: 26.2185,
      lng: 50.6071,
      placeId: null,
    },
    description:
      "Gravity Indoor Skydiving offers an exhilarating experience with state-of-the-art vertical wind tunnels. Safe for all ages, it's a perfect place for thrill-seekers to experience the sensation of free-fall without actually jumping from a plane.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Indoor Skydiving Center",
    priceRange: "Moderate",
    email: "info@gravityskydiving.bh",
    phoneNumber: "+973 1234 5678",
    website: "gravityskydiving.bh",
    locationRate: 0,
    safety: 0,
    facilities: 0,
    convenience: 0,
    staff: 0,
    duration: "1 hour",
    activityType: ["skydiving simulations"],
    accessibility: ["Wheelchair Accessible", "Family-Friendly"],
    whatToExpect: [
      "Thrilling skydiving experience",
      "Advanced safety measures",
      "Fun for all ages",
    ],
  },
  {
    name: "Moda Mall Bahrain World Trade Center",
    region: "Capital",
    category: "thingsToDo",
    subTags: [
      "shopping",
      "luxury brands",
      "high-end shopping",
      "designer labels",
      "fashion",
      "jewelry",
      "watches",
      "family-friendly",
      "friends",
      "solo",
    ],
    rate: 4,
    location: "Manama, Bahrain",
    googleLocation: {
      lat: 26.2426,
      lng: 50.5831,
      placeId: null,
    },
    description:
      "Located at the iconic Bahrain World Trade Center, Moda Mall hosts an array of high-end luxury brands and designer labels, making it a top destination for upscale shopping. The mall's elegant ambiance and variety of dining options enhance the shopping experience.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Luxury Shopping Mall",
    priceRange: "High",
    email: "info@modamall.bh",
    phoneNumber: "+973 1234 5678",
    website: "modamall.bh",
    locationRate: 0,
    safety: 0,
    facilities: 0,
    convenience: 0,
    staff: 0,
    duration: "2 - 4 hours",
    activityType: ["shopping", "dining"],
    accessibility: ["Wheelchair Accessible", "Family-Friendly"],
    whatToExpect: [
      "Upscale shopping experience",
      "Wide range of luxury products",
      "Elegant dining options",
    ],
  },
  // resturants thingsToDo places
  {
    name: "Maki Bahrain",
    region: "Capital",
    category: "thingsToEat",
    subTags: [
      "Japanese",
      "sushi",
      "upscale",
      "dining experience",
      "luxury",
      "gourmet",
      "friends",
      "family",
      "business",
    ],
    rate: 4.5,
    location:
      "Bahrain World Trade Center West Tower, King Faisal Highway, Manama 2535 Bahrain",
    googleLocation: {
      lat: 26.2426, // Approximate coordinates of the World Trade Center
      lng: 50.5831,
      placeId: null,
    },
    description:
      "Maki Bahrain, located at the World Trade Center, offers a luxurious dining experience with a wide array of sushi and Japanese cuisine. Known for its innovative dishes and upscale ambiance, it's perfect for both social and business gatherings.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Japanese Restaurant",
    priceRange: "30 - 40 BHD",
    email: "contact@makibahrain.bh", // Assumed
    phoneNumber: "+973 3699 9102",
    website: "www.makibahrain.com",
    foodQuality: 0,
    valueForMoney: 0,
    service: 0,
    menuVariety: 0,
    ambiance: 0,
    cuisines: ["Japanese", "Sushi", "Asian"],
    specialDiets: ["Vegetarian Friendly", "Gluten Free Options"],
    meals: ["Lunch", "Dinner"],
    featuresList: [
      "Reservations",
      "Seating",
      "Waitstaff",
      "Serves Alcohol",
      "Full Bar",
      "Private Dining",
    ],
  },
  {
    name: "Monsoon",
    region: "Capital",
    category: "thingsToEat",
    subTags: [
      "Asian cuisine",
      "Thai",
      "Vietnamese",
      "elegant",
      "romantic",
      "dining experience",
      "luxury",
      "friends",
      "date night",
    ],
    rate: 4.5,
    location: "Adliya, Manama, Bahrain",
    googleLocation: {
      lat: 26.2117, // Approximate coordinates of Adliya
      lng: 50.5951,
      placeId: null,
    },
    description:
      "Monsoon treats diners to a sophisticated atmosphere with a blend of Thai and Vietnamese cuisine. Known for its elegant decor and tranquil ambiance, it's a favorite for romantic dinners and special occasions.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Asian Fusion Restaurant",
    priceRange: "15 - 30 BHD",
    email: "info@monsoonbahrain.com", // Assumed
    phoneNumber: "+973 1774 9222",
    website: "www.monsoonbahrain.com",
    foodQuality: 0,
    valueForMoney: 0,
    service: 0,
    menuVariety: 0,
    ambiance: 0,
    cuisines: ["Thai", "Vietnamese", "Asian Fusion"],
    specialDiets: [
      "Vegetarian Friendly",
      "Vegan Options",
      "Gluten Free Options",
    ],
    meals: ["Lunch", "Dinner", "Late Night"],
    featuresList: [
      "Reservations",
      "Outdoor Seating",
      "Private Dining",
      "Seating",
      "Serves Alcohol",
      "Full Bar",
      "Free Wifi",
    ],
  },
  {
    name: "Coco's",
    region: "Capital",
    category: "thingsToEat",
    subTags: [
      "cafe",
      "casual dining",
      "local cuisine",
      "fresh ingredients",
      "friends",
      "family",
      "relaxed",
    ],
    rate: 4,
    location: "Adliya, Manama, Bahrain",
    googleLocation: {
      lat: 26.2124,
      lng: 50.5915,
      placeId: null,
    },
    description:
      "Coco's, nestled in the vibrant Adliya district, offers a casual dining experience with a focus on fresh, local ingredients. Popular among locals and tourists alike, the cafe is famed for its laid-back atmosphere and delightful menu.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Cafe",
    priceRange: "10 - 20 BHD",
    email: "contact@cocosbahrain.com", // Assumed
    phoneNumber: "+973 1771 6512",
    website: "www.cocoscafe.com",
    foodQuality: 0,
    valueForMoney: 0,
    service: 0,
    menuVariety: 0,
    ambiance: 0,
    cuisines: ["International", "Cafe", "European"],
    specialDiets: ["Vegetarian Friendly", "Vegan Options"],
    meals: ["Breakfast", "Brunch", "Lunch", "Dinner"],
    featuresList: [
      "Outdoor Seating",
      "Seating",
      "Highchairs Available",
      "Serves Alcohol",
      "Free Wifi",
    ],
  },
  {
    name: "Rasoi by Vineet",
    region: "Capital",
    category: "thingsToEat",
    subTags: [
      "Indian cuisine",
      "Michelin-star chef",
      "gourmet",
      "luxury dining",
      "friends",
      "business meetings",
      "romantic",
    ],
    rate: 5,
    location: "Manama, Bahrain",
    googleLocation: {
      lat: 26.2405, // Approximate coordinates for central Manama
      lng: 50.5867,
      placeId: null,
    },
    description:
      "Rasoi by Vineet is Bahrain's first fine dining restaurant managed by a Michelin-starred chef, Vineet Bhatia. It offers a unique blend of traditional and modern Indian cuisine, creating a luxurious dining experience.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Fine Dining Indian Restaurant",
    priceRange: "25 - 50 BHD",
    email: "dine@rasoibyvineet.bh", // Assumed
    phoneNumber: "+973 1764 6464",
    website: "www.rasoibyvineet.com",
    foodQuality: 0,
    valueForMoney: 0,
    service: 0,
    menuVariety: 0,
    ambiance: 0,
    cuisines: ["Indian"],
    specialDiets: [
      "Vegetarian Friendly",
      "Vegan Options",
      "Gluten Free Options",
    ],
    meals: ["Lunch", "Dinner"],
    featuresList: [
      "Reservations",
      "Private Dining",
      "Seating",
      "Waitstaff",
      "Serves Alcohol",
      "Full Bar",
    ],
  },
  {
    name: "Sherlock Holmes Pub",
    region: "Capital",
    category: "thingsToEat",
    subTags: [
      "pub",
      "British cuisine",
      "casual dining",
      "live music",
      "sports bar",
      "friends",
      "nightlife",
    ],
    rate: 4,
    location: "Manama, Bahrain",
    googleLocation: {
      lat: 26.2297,
      lng: 50.576,
      placeId: null,
    },
    description:
      "Sherlock Holmes Pub offers a classic British pub experience with a selection of beers and traditional pub food. Known for its lively atmosphere, it's a great spot for watching sports, enjoying live music, and spending a relaxed evening.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Pub",
    priceRange: "10 - 30 BHD",
    email: "info@sherlockholmespub.bh", // Assumed
    phoneNumber: "+973 1771 3000",
    website: "www.sherlockholmespub.bh",
    foodQuality: 0,
    valueForMoney: 0,
    service: 0,
    menuVariety: 0,
    ambiance: 0,
    cuisines: ["British", "Pub"],
    specialDiets: ["Vegetarian Friendly"],
    meals: ["Lunch", "Dinner", "Late Night"],
    featuresList: [
      "Live Music",
      "Televised Sports",
      "Outdoor Seating",
      "Serves Alcohol",
      "Full Bar",
    ],
  },
  {
    name: "Cafe Lilou",
    region: "Capital",
    category: "thingsToEat",
    subTags: [
      "cafe",
      "French patisserie",
      "artisanal",
      "cozy",
      "romantic",
      "friends",
      "breakfast",
      "brunch",
    ],
    rate: 4.5,
    location: "Adliya, Manama, Bahrain",
    googleLocation: {
      lat: 26.2124,
      lng: 50.5915,
      placeId: null,
    },
    description:
      "Cafe Lilou is an artisanal French patisserie and cafe known for its elaborate decor and cozy ambiance, making it a popular spot for breakfast and brunch. The menu features a wide range of French pastries, gourmet sandwiches, and specialty coffees.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Cafe",
    priceRange: "10 - 20 BHD",
    email: "info@cafelilou.com", // Assumed
    phoneNumber: "+973 1771 4440",
    website: "www.cafelilou.com",
    foodQuality: 0,
    valueForMoney: 0,
    service: 0,
    menuVariety: 0,
    ambiance: 0,
    cuisines: ["French", "European", "Cafe"],
    specialDiets: ["Vegetarian Friendly", "Gluten Free Options"],
    meals: ["Breakfast", "Brunch", "Lunch", "Dinner"],
    featuresList: [
      "Reservations",
      "Seating",
      "Waitstaff",
      "Highchairs Available",
      "Serves Alcohol",
      "Outdoor Seating",
      "Free Wifi",
    ],
  },
  {
    name: "Fish Market Restaurant",
    region: "Capital",
    category: "thingsToEat",
    subTags: [
      "seafood",
      "fresh fish",
      "market style",
      "family",
      "casual dining",
      "sea view",
    ],
    rate: 4,
    location: "Manama Corniche, Manama, Bahrain",
    googleLocation: {
      lat: 26.2405,
      lng: 50.5867,
      placeId: null,
    },
    description:
      "Fish Market Restaurant offers a unique dining experience where guests can choose their fresh seafood directly from a market-style display. Located on the Manama Corniche, it provides beautiful sea views and a casual yet refined dining atmosphere.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Seafood Restaurant",
    priceRange: "15 - 30 BHD",
    email: "info@fishmarketbahrain.com", // Assumed
    phoneNumber: "+973 1723 1234",
    website: "www.fishmarketbahrain.com",
    foodQuality: 0,
    valueForMoney: 0,
    service: 0,
    menuVariety: 0,
    ambiance: 0,
    cuisines: ["Seafood"],
    specialDiets: ["Vegetarian Friendly", "Gluten Free Options"],
    meals: ["Lunch", "Dinner"],
    featuresList: [
      "Market Style Selection",
      "Outdoor Seating",
      "Sea View",
      "Alcohol Served",
    ],
  },
  {
    name: "Trader Vic's Restaurant & Lounge",
    region: "Capital",
    category: "thingsToEat",
    subTags: [
      "Polynesian",
      "tropical",
      "exotic drinks",
      "live music",
      "lounge",
      "friends",
      "night out",
    ],
    rate: 4,
    location: "Ritz-Carlton Bahrain, Manama, Bahrain",
    googleLocation: {
      lat: 26.2405,
      lng: 50.5867,
      placeId: null,
    },
    description:
      "Trader Vic's, located at the Ritz-Carlton Bahrain, offers a unique Polynesian-themed dining experience with an exotic menu and signature cocktails. Known for its vibrant atmosphere and live music, it's a favorite spot for a lively night out.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Restaurant & Lounge",
    priceRange: "20 - 40 BHD",
    email: "info@tradervicsbahrain.com", // Assumed
    phoneNumber: "+973 1758 6555",
    website: "www.tradervicsbahrain.com",
    foodQuality: 0,
    valueForMoney: 0,
    service: 0,
    menuVariety: 0,
    ambiance: 0,
    cuisines: ["Polynesian", "Asian", "International"],
    specialDiets: ["Vegetarian Friendly"],
    meals: ["Dinner"],
    featuresList: [
      "Live Music",
      "Bar",
      "Lounge Seating",
      "Reservations",
      "Outdoor Seating",
    ],
  },
  {
    name: "Buffalo Wings & Rings",
    region: "Capital",
    category: "thingsToEat",
    subTags: [
      "American cuisine",
      "sports bar",
      "wings",
      "casual dining",
      "friends",
      "family-friendly",
      "sports",
    ],
    rate: 4,
    location: "Juffair, Manama, Bahrain",
    googleLocation: {
      lat: 26.2181,
      lng: 50.5971,
      placeId: null,
    },
    description:
      "Buffalo Wings & Rings is a lively sports bar known for its American-style chicken wings and a great selection of beers. With multiple screens to catch live sports events, it's a popular spot for both locals and expats to gather and enjoy a fun, casual atmosphere.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Sports Bar",
    priceRange: "10 - 25 BHD",
    email: "info@bwr-bahrain.com", // Assumed
    phoneNumber: "+973 1600 0000",
    website: "www.buffalowingsandrings.com",
    foodQuality: 0,
    valueForMoney: 0,
    service: 0,
    menuVariety: 0,
    ambiance: 0,
    cuisines: ["American", "Bar Food"],
    specialDiets: ["Gluten Free Options"],
    meals: ["Lunch", "Dinner", "Late Night"],
    featuresList: [
      "Live Sports",
      "Outdoor Seating",
      "Alcohol Served",
      "Family-Friendly",
      "Takeout",
      "Reservations",
    ],
  },
  {
    name: "Bushido by Buddha Bar",
    region: "Capital",
    category: "thingsToEat",
    subTags: [
      "Japanese",
      "luxury dining",
      "sushi",
      "upscale",
      "friends",
      "business meetings",
      "nightlife",
    ],
    rate: 4.5,
    location: "Seef Area, Manama, Bahrain",
    googleLocation: {
      lat: 26.2477,
      lng: 50.5417,
      placeId: null,
    },
    description:
      "Bushido by Buddha Bar is an upscale restaurant offering a unique blend of Japanese cuisine with a sophisticated twist. Inspired by the code of the Samurai, the decor is opulent and the ambiance is suited for luxurious nights out and important business dinners.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Fine Dining Restaurant",
    priceRange: "30 - 50 BHD",
    email: "info@bushidobybuddhabar.com", // Assumed
    phoneNumber: "+973 1758 3555",
    website: "www.bushidobybuddhabar.com",
    foodQuality: 0,
    valueForMoney: 0,
    service: 0,
    menuVariety: 0,
    ambiance: 0,
    cuisines: ["Japanese", "Asian Fusion"],
    specialDiets: [
      "Vegetarian Friendly",
      "Vegan Options",
      "Gluten Free Options",
    ],
    meals: ["Lunch", "Dinner"],
    featuresList: [
      "Reservations",
      "Seating",
      "Waitstaff",
      "Serves Alcohol",
      "Bar",
      "Private Dining",
      "Valet Parking",
    ],
  },
  // places to stay hotels
  {
    name: "Intercontinental Bahrain",
    region: "Capital",
    category: "placesToStay",
    subTags: [
      "luxury",
      "business hotel",
      "conference",
      "spa",
      "central location",
      "family-friendly",
      "tourist",
    ],
    rate: 5,
    location: "King Faisal Highway, Manama, Bahrain",
    googleLocation: {
      lat: 26.2418, // Approximate coordinates for central Manama
      lng: 50.5878,
      placeId: null,
    },
    description:
      "Intercontinental Bahrain, located in the heart of Manama, offers luxury accommodations and top-notch facilities, including a spa, several dining options, and extensive conference facilities. It is ideal for both business travelers and tourists looking for a central and comfortable stay.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Luxury Hotel",
    priceRange: "120 - 250 BHD",
    email: "info@icbahrain.bh", // Assumed
    phoneNumber: "+973 1722 7777",
    website: "www.icbahrain.com",
    serviceRate: 0,
    roomQuality: 0,
    cleanliness: 0,
    accommodationType: ["Deluxe Rooms", "Executive Rooms", "Suites"],
    amenities: [
      "High-speed Wi-Fi",
      "spa",
      "multiple restaurants",
      "conference facilities",
      "outdoor pool",
    ],
    roomType: ["Standard Rooms", "Executive Rooms", "Suites"],
    locationType:
      "In the heart of Manama, near business districts and cultural sites",
    additionalServices: [
      "airport shuttle",
      "24-hour room service",
      "car rental desk",
      "currency exchange",
    ],
    languagesSpoken: ["English", "Arabic", "Hindi"],
    hotelClass: 5,
  },
  {
    name: "Sofitel Bahrain Zallaq Thalassa sea & spa",
    region: "Southern",
    category: "placesToStay",
    subTags: [
      "luxury",
      "beachfront",
      "thalassotherapy",
      "spa",
      "family-friendly",
      "romantic",
      "tourist",
    ],
    rate: 5,
    location: "105 Zallaq Highway, Zallaq, Manama, Bahrain",
    googleLocation: {
      lat: 26.0687,
      lng: 50.5069,
      placeId: null,
    },
    description:
      "The Sofitel Bahrain Zallaq Thalassa sea & spa is a luxury resort offering exclusive beach access and the only thalassotherapy spa in Bahrain. With French-inspired hospitality, the resort combines relaxation with sophistication, perfect for family vacations or romantic getaways.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Luxury Resort",
    priceRange: "150 - 300 BHD",
    email: "H6722@sofitel.com",
    phoneNumber: "+973 1763 6363",
    website: "www.sofitel-bahrain-zallaq-thalassa.com",
    serviceRate: 0,
    roomQuality: 0,
    cleanliness: 0,
    accommodationType: ["Deluxe Rooms", "Executive Rooms", "Suites"],
    amenities: [
      "Private beach",
      "Thalassotherapy spa",
      "Fine dining restaurants",
      "Fitness center",
      "Kids club",
    ],
    roomType: ["Standard Rooms", "Sea View Rooms", "Suites"],
    locationType:
      "Beachfront on Zallaq Highway, offering serene views and direct beach access",
    additionalServices: [
      "Water sports",
      "Yoga classes",
      "Kids activities",
      "Conference facilities",
    ],
    languagesSpoken: ["English", "Arabic", "French"],
    hotelClass: 5,
  },
  {
    name: "Hilton Bahrain",
    region: "Capital",
    category: "placesToStay",
    subTags: [
      "business hotel",
      "luxury",
      "family-friendly",
      "conference",
      "central location",
      "modern amenities",
    ],
    rate: 5,
    location: "Seef District, Manama, Bahrain",
    googleLocation: {
      lat: 26.2429,
      lng: 50.5479,
      placeId: null,
    },
    description:
      "Hilton Bahrain, situated in Manama’s vibrant Seef district, features modern amenities and luxurious accommodations. Catering to both business and leisure travelers, the hotel offers extensive meeting spaces, a fitness center, and several dining options.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Hotel",
    priceRange: "100 - 220 BHD",
    email: "info@hiltonbahrain.com",
    phoneNumber: "+973 1758 0000",
    website: "www.hilton.com/en/hotels/bahrain",
    serviceRate: 0,
    roomQuality: 0,
    cleanliness: 0,
    accommodationType: [
      "Deluxe Rooms",
      "Executive Rooms",
      "Suites",
      "Accessible Rooms",
    ],
    amenities: [
      "Conference center",
      "Fitness center",
      "Outdoor pool",
      "Multiple dining options",
      "Spa",
    ],
    roomType: ["Standard Rooms", "Executive Rooms", "Suites"],
    locationType:
      "In the bustling Seef district, close to shopping and business areas",
    additionalServices: [
      "Executive lounge",
      "Valet parking",
      "Airport shuttle",
      "24-hour concierge",
    ],
    languagesSpoken: ["English", "Arabic"],
    hotelClass: 5,
  },
  {
    name: "Gulf Hotel Bahrain Convention and Spa",
    region: "Capital",
    category: "placesToStay",
    subTags: [
      "luxury",
      "business hotel",
      "spa",
      "convention center",
      "family-friendly",
      "culinary experience",
    ],
    rate: 5,
    location: "Al Fateh Avenue, Manama, Bahrain",
    googleLocation: {
      lat: 26.2235,
      lng: 50.5957,
      placeId: null,
    },
    description:
      "Located centrally in Manama, Gulf Hotel Bahrain offers luxury accommodations with a large convention center, making it a preferred choice for business events and conferences. The hotel also features a comprehensive spa and multiple dining options, providing a rich culinary experience.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Hotel",
    priceRange: "100 - 200 BHD",
    email: "info@gulfhotelbahrain.com",
    phoneNumber: "+973 1771 3000",
    website: "www.gulfhotelbahrain.com",
    serviceRate: 0,
    roomQuality: 0,
    cleanliness: 0,
    accommodationType: ["Deluxe Rooms", "Executive Rooms", "Suites"],
    amenities: [
      "Convention center",
      "Spa",
      "Multiple restaurants",
      "Outdoor pool",
      "Fitness center",
    ],
    roomType: ["Standard Rooms", "Executive Rooms", "Suites"],
    locationType:
      "Central location in Manama, convenient for both business and leisure",
    additionalServices: [
      "Airport shuttle",
      "24-hour room service",
      "Business services",
      "Babysitting",
    ],
    languagesSpoken: ["English", "Arabic", "Hindi"],
    hotelClass: 5,
  },

  {
    name: "Movenpick Hotel Bahrain",
    region: "Muharraq",
    category: "placesToStay",
    subTags: [
      "luxury",
      "airport hotel",
      "business facilities",
      "family-friendly",
      "modern amenities",
    ],
    rate: 5,
    location: "143 Road 2403, Al Muharraq, Bahrain",
    googleLocation: {
      lat: 26.2707,
      lng: 50.6337,
      placeId: null,
    },
    description:
      "Movenpick Hotel Bahrain is conveniently located near the airport, offering easy access for travelers. The hotel boasts modern amenities, a variety of dining options, and excellent business facilities, including conference rooms and a business center.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Hotel",
    priceRange: "90 - 180 BHD",
    email: "info@movenpick-bahrain.com",
    phoneNumber: "+973 1746 0000",
    website: "www.movenpick.com/bahrain",
    serviceRate: 0,
    roomQuality: 0,
    cleanliness: 0,
    accommodationType: ["Deluxe Rooms", "Superior Rooms", "Suites"],
    amenities: [
      "Business center",
      "Multiple dining options",
      "Spa",
      "Outdoor pool",
      "Fitness center",
    ],
    roomType: ["Standard Rooms", "Superior Rooms", "Suites"],
    locationType:
      "Near Bahrain International Airport, ideal for transit travelers and short stays",
    additionalServices: [
      "Airport shuttle",
      "Car rental desk",
      "Laundry services",
      "24-hour front desk",
    ],
    languagesSpoken: ["English", "Arabic", "French"],
    hotelClass: 5,
  },
  {
    name: "The Ritz-Carlton Bahrain",
    region: "Capital",
    category: "placesToStay",
    subTags: [
      "luxury",
      "beach resort",
      "spa",
      "family-friendly",
      "exclusive",
      "gourmet dining",
    ],
    rate: 5,
    location:
      "Building 112, King Mohammed VI Ave, Block 428, Al Seef, Manama, Bahrain",
    googleLocation: {
      lat: 26.2421,
      lng: 50.5472,
      placeId: null,
    },
    description:
      "The Ritz-Carlton Bahrain is an exclusive beach resort that offers luxurious accommodations and exceptional service. The resort features a private beach, a world-class spa, and gourmet dining options, catering to the most discerning travelers.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Luxury Resort",
    priceRange: "200 - 400 BHD",
    email: "rc.bahrz.reservations@ritzcarlton.com",
    phoneNumber: "+973 1758 0000",
    website: "www.ritzcarlton.com/bahrain",
    serviceRate: 0,
    roomQuality: 0,
    cleanliness: 0,
    accommodationType: ["Deluxe Rooms", "Club Rooms", "Suites"],
    amenities: [
      "Private beach",
      "Spa",
      "Fine dining",
      "Fitness center",
      "Tennis courts",
    ],
    roomType: ["Standard Rooms", "Club Rooms", "Suites"],
    locationType:
      "Beachfront in Al Seef district, offering a blend of luxury and exclusivity",
    additionalServices: [
      "Yacht rental",
      "Kids club",
      "Personal concierge service",
      "Valet parking",
    ],
    languagesSpoken: ["English", "Arabic", "Italian", "French"],
    hotelClass: 5,
  },
  {
    name: "Crowne Plaza Manama Bahrain",
    region: "Capital",
    category: "placesToStay",
    subTags: [
      "business hotel",
      "luxury",
      "central location",
      "conference facilities",
      "family-friendly",
    ],
    rate: 4.5,
    location: "Diplomatic Area, Manama, Bahrain",
    googleLocation: {
      lat: 26.2416,
      lng: 50.5952,
      placeId: null,
    },
    description:
      "Located in the heart of the diplomatic area, Crowne Plaza Manama is ideally suited for business travelers with its extensive conference facilities. The hotel also caters to leisure travelers with its luxurious amenities, including a swimming pool and multiple dining options.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Hotel",
    priceRange: "80 - 160 BHD",
    email: "info@cpmanama.com",
    phoneNumber: "+973 1753 1122",
    website: "www.cpmanama.com",
    serviceRate: 0,
    roomQuality: 0,
    cleanliness: 0,
    accommodationType: ["Standard Rooms", "Executive Rooms", "Suites"],
    amenities: [
      "Conference facilities",
      "Outdoor pool",
      "Multiple dining options",
      "Fitness center",
    ],
    roomType: ["Standard Rooms", "Executive Rooms", "Suites"],
    locationType:
      "Centrally located in the diplomatic area, close to government offices and shopping centers",
    additionalServices: ["Valet parking", "Airport shuttle", "Business center"],
    languagesSpoken: ["English", "Arabic", "Hindi"],
    hotelClass: 5,
  },
  {
    name: "Downtown Rotana",
    region: "Capital",
    category: "placesToStay",
    subTags: [
      "modern hotel",
      "business and leisure",
      "city center",
      "luxury",
      "stylish",
    ],
    rate: 5,
    location: "Government Avenue, Manama, Bahrain",
    googleLocation: {
      lat: 26.2335,
      lng: 50.5732,
      placeId: null,
    },
    description:
      "Downtown Rotana is situated in the heart of Manama, offering stylish and contemporary accommodations. Ideal for both business and leisure travelers, the hotel features state-of-the-art facilities including meeting rooms, a fitness center, and a rooftop pool.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Hotel",
    priceRange: "90 - 180 BHD",
    email: "info@downtownrotana.com",
    phoneNumber: "+973 1311 9999",
    website: "www.rotana.com/downtownrotana",
    serviceRate: 0,
    roomQuality: 0,
    cleanliness: 0,
    accommodationType: ["Deluxe Rooms", "Club Rooms", "Suites"],
    amenities: [
      "Rooftop pool",
      "Fitness center",
      "Spa",
      "Multiple dining options",
    ],
    roomType: ["Standard Rooms", "Deluxe Rooms", "Suites"],
    locationType:
      "In the bustling heart of Manama, near business, shopping, and entertainment districts",
    additionalServices: [
      "Concierge service",
      "Limousine service",
      "24-hour room service",
    ],
    languagesSpoken: ["English", "Arabic", "French"],
    hotelClass: 5,
  },
  {
    name: "The Westin City Centre Bahrain",
    region: "Capital",
    category: "placesToStay",
    subTags: [
      "luxury",
      "shopping complex",
      "family-friendly",
      "business hotel",
      "spa",
    ],
    rate: 4.5,
    location: "City Centre Bahrain, Manama, Bahrain",
    googleLocation: {
      lat: 26.2305,
      lng: 50.5834,
      placeId: null,
    },
    description:
      "Connected to City Centre Bahrain, The Westin offers luxurious rooms and superb amenities. A favorite among families and business travelers, it features direct access to one of the largest shopping malls in Bahrain, a renowned spa, and multiple dining options.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Hotel",
    priceRange: "100 - 220 BHD",
    email: "info@westinbahraincitycentre.com",
    phoneNumber: "+973 1717 1000",
    website: "www.westinbahraincitycentre.com",
    serviceRate: 0,
    roomQuality: 0,
    cleanliness: 0,
    accommodationType: ["Deluxe Rooms", "Executive Rooms", "Suites"],
    amenities: [
      "Connected to shopping mall",
      "Spa",
      "Fitness center",
      "Kids club",
    ],
    roomType: ["Standard Rooms", "Executive Rooms", "Suites"],
    locationType:
      "Directly connected to City Centre Bahrain, offering extensive shopping and entertainment options",
    additionalServices: [
      "Meeting facilities",
      "Valet parking",
      "Kids activities",
    ],
    languagesSpoken: ["English", "Arabic"],
    hotelClass: 5,
  },
  {
    name: "Wyndham Garden Manama",
    region: "Capital",
    category: "placesToStay",
    subTags: [
      "business hotel",
      "modern amenities",
      "family-friendly",
      "multi-cuisine dining",
      "accessible",
    ],
    rate: 4,
    location: "Juffair, Manama, Bahrain",
    googleLocation: {
      lat: 26.2183,
      lng: 50.5996,
      placeId: null,
    },
    description:
      "Wyndham Garden Manama is located in the lively Juffair area, featuring modern and comfortable accommodations suitable for both business and leisure travelers. The hotel boasts multiple dining options, a fitness center, and spacious meeting rooms.",
    comments: [],
    photos: [],
    totalComments: 0,
    imagePlace: "",
    type: "Hotel",
    priceRange: "70 - 140 BHD",
    email: "info@wyndhamgardenmanama.com",
    phoneNumber: "+973 6631 6666",
    website: "www.wyndhamgardenmanama.com",
    serviceRate: 0,
    roomQuality: 0,
    cleanliness: 0,
    accommodationType: ["Standard Rooms", "Executive Rooms", "Suites"],
    amenities: [
      "Multi-cuisine restaurants",
      "Fitness center",
      "Spa",
      "Meeting rooms",
    ],
    roomType: ["Standard Rooms", "Executive Rooms", "Suites"],
    locationType:
      "In the vibrant area of Juffair, close to nightlife and shopping centers",
    additionalServices: [
      "Airport shuttle",
      "Concierge service",
      "Childcare services",
    ],
    languagesSpoken: ["English", "Arabic"],
    hotelClass: 4,
  },
];
